// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAHZmAtMUHbtGJa4NOBSypxLX8rs2AKHxc',
    appId: '1:566155530467:web:ee64c2064e67c879f675d6',
    messagingSenderId: '566155530467',
    projectId: 'social-app-f53bd',
    authDomain: 'social-app-f53bd.firebaseapp.com',
    storageBucket: 'social-app-f53bd.appspot.com',
    measurementId: 'G-B6STJKVNRK',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBNHi2CO6fO77Ndzusd6cbpybBZig4Q5hE',
    appId: '1:566155530467:android:161675b40b63fd87f675d6',
    messagingSenderId: '566155530467',
    projectId: 'social-app-f53bd',
    storageBucket: 'social-app-f53bd.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAyEvwqisTJK3ts49-0x_ZqyCD85NUx10o',
    appId: '1:566155530467:ios:22a1e8fec781a92ef675d6',
    messagingSenderId: '566155530467',
    projectId: 'social-app-f53bd',
    storageBucket: 'social-app-f53bd.appspot.com',
    iosClientId: '566155530467-n3b4a6qlar5nmkiitit78fnolvl912r4.apps.googleusercontent.com',
    iosBundleId: 'com.example.social',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAyEvwqisTJK3ts49-0x_ZqyCD85NUx10o',
    appId: '1:566155530467:ios:22a1e8fec781a92ef675d6',
    messagingSenderId: '566155530467',
    projectId: 'social-app-f53bd',
    storageBucket: 'social-app-f53bd.appspot.com',
    iosClientId: '566155530467-n3b4a6qlar5nmkiitit78fnolvl912r4.apps.googleusercontent.com',
    iosBundleId: 'com.example.social',
  );
}
